### ISSUE TITLE
sqlite bug and mulit line error

### ISSUE THREAD

**Issue by LexShadow** [thenullnetwork/chat#4]
Form the last comments I posted you I can confirm the second bug is to do with the sqlite option, I enabled mysql what I didn't want to but for testing it's fine, and it works fine with that but now when I install it with that I get 

`Notice: Undefined index: multi in index.php on line 1732`

I believe you just need to do a check for that as I muted it with @ and the chat loaded.

**Comment by LexShadow** [comment]
Another problem I found is if I reload the the chat with the chat button it reloads the root not the sub folder the chat's in.

**Comment by LexShadow** [comment]
You might want to change 
`href="/index.php?`
to
`href="./index.php?`

**Comment by LexShadow** [comment]
ALso now do I get the emojis to work?

**Comment by d-a-s-h-o** [comment]
> You might want to change 
> 
> `href="/index.php?`
> 
> to
> 
> `href="./index.php?`
> 
> 
> 
> I can confirm this worked change all your links from/ or file to ./ and ./file
> 
> 
> 
> Edit line 1054
> 
> `'.$I[room].'`
> 
> to
> 
> `'.$I['room'].'`

Thanks for this info... I'll make sure to do so

**Comment by d-a-s-h-o** [comment]
> ALso now do I get the emojis to work?

There is a series of three reflex filters you need to add to the filters list... will attach soon

**Comment by d-a-s-h-o** [comment]
> Form the last comments I posted you I can confirm the second bug is to do with the sqlite option, I enabled mysql what I didn't want to but for testing it's fine, and it works fine with that but now when I install it with that I get 
> 
> 
> 
> `Notice: Undefined index: multi in index.php on line 1732`
> 

Yep that's probably missing the `''` around them.

> 
> I believe you just need to do a check for that as I muted it with @ and the chat loaded.

I seem to have a lot to fix... wonder why it has worked for me up to now as I am using the exact same script for my one lol

**Comment by LexShadow** [comment]
Depends on platform and php keep this post as open and I will keep adding little fix's time after time, I don't have time to fork, fix and push as well I kinda don't even know how that works very well lol

**Comment by d-a-s-h-o** [comment]
Yo ... Here is a (verified) working copy of the repository: https://git.onionz.dev/thenullnetwork/chatterbox
This will work perfectly (should) with MySQL and hopefully with MySQLite... I also included the [emojifilters.md](https://git.onionz.dev/thenullnetwork/chatterbox/blob/master/emojifilters.md) and [filtersBackup.md](https://git.onionz.dev/thenullnetwork/chatterbox/blob/master/filtersBackup.md) files which will allow you to add in all the emojis. Like I said this is a rough project and I havn't done much on it in ages.... been working mostly on a hosting solution rather than this lol, but have a look and hopefully that will work fine. If so I might see about cloning that into this repository.

One thing to notice is the $devmode. I have this set to off which will hide some errors (I know it's kinda cheating but the one error it's showing doesn't actually affect the functionality of it so it's fine), you can turn this to one when setting up the chat if you want, but make sure to turn back to 0 for production. :)

Hope this helps...

**Comment by LexShadow** [comment]
I will give this a test later today or tomorrow for you via sqlite, since this is what I want to use over mysql I would use basic flat file is I could be bothered righting a db scheme for it lol but never got around to doing it.

And hey your doing a good job, don't worry about not always getting to it.

**Comment by d-a-s-h-o** [comment]
> I will give this a test later today or tomorrow for you via sqlite, since this is what I want to use over mysql I would use basic flat file is I could be bothered righting a db scheme for it lol but never got around to doing it.
> 
> And hey your doing a good job, don't worry about not always getting to it.

Any luck?

**Comment by LexShadow** [comment]
I couldn't get this to work but if you update the core parts of the chat to the new one from Dan he added a few more things what yours needs and also the fix to the sql thing.

**Comment by d-a-s-h-o** [comment]
New release fixes this issue.
